version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: claude-chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ${HOME}/.claude/data/chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - ALLOW_RESET=TRUE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network

  # Optional: Qdrant (high-performance alternative)
  # Uncomment to use Qdrant instead of Chroma
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   container_name: claude-qdrant
  #   restart: unless-stopped
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - ${HOME}/.claude/qdrant-data:/qdrant/storage
  #   environment:
  #     - QDRANT__TELEMETRY_DISABLED=true
  #   networks:
  #     - claude-network

  # Optional: Ollama for local embeddings (zero API cost)
  # Uncomment to run embeddings locally
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: claude-ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ${HOME}/.claude/ollama-data:/root/.ollama
  #   networks:
  #     - claude-network

networks:
  claude-network:
    driver: bridge
    name: claude-network
