version: '3.8'

services:
  # Chroma Vector Database (Primary - Recommended)
  chroma:
    image: chromadb/chroma:latest
    container_name: claude-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Qdrant (Optional - High Performance Alternative)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: claude-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    profiles:
      - optional
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama (Optional - Local Embeddings)
  ollama:
    image: ollama/ollama:latest
    container_name: claude-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    restart: unless-stopped
    profiles:
      - optional
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma-data:
    driver: local
  qdrant-data:
    driver: local
  ollama-data:
    driver: local

networks:
  default:
    name: claude-network
